version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: '[actions] '
    open-pull-requests-limit: 5
    groups:
      actions-minor:
        update-types:
          - minor
          - patch
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: '[node] '
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
    groups:
      development:
        dependency-type: development
        update-types:
          - minor
          - patch
      production:
        dependency-type: production
        update-types:
          - minor
          - patch
  - package-ecosystem: 'docker'
    directory: /
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: '[docker] '
    open-pull-requests-limit: 5
